### ISSUE TITLE
potion is not displayed in gui

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/Challenges#290]
### Expected behavior

the name of potions is not displayed on the challenge gui.
![image](https://user-images.githubusercontent.com/22028655/148621283-04dd235a-e4f3-4ed0-8a88-b46cc8cb2216.png)

### Observed/Actual behavior

not name

### Steps/models to reproduce

in challenge

### BentoBox version

1.20.0

![image](https://user-images.githubusercontent.com/22028655/148621406-00b518b8-6ae4-40a7-b16a-cfc2b5c79ea4.png)

**Comment by BONNe** [comment]
By default, potions will be translated like that. 

However, you can enable precise translation with locales files (/plugins/bentobox/locales/challenges):

https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/resources/locales/en-US.yml#L1214-L1241

In my server I use like this:
```
  item-stacks:
    meta:
      upgraded: 'Upgraded '
      extended: 'Extended '
    potion:
      name: '[upgraded][extended]Potion of [type]'
    splash_potion:
      name: '[upgraded][extended]Splash Potion of [type]'
    lingering_potion:
      name: '[upgraded][extended]Lingering Potion of [type]'
```      

By default, it is not added... I even do not remember the reason... but well, it can be enabled :D
